- question: "Where are you licensed to work?"
  answer: "I am licensed in Colorado and Washington DC. I offer telehealth appointments."

- question: "Do you offer free consultations to see if we're a good fit?"
  answer: "Yes, I offer a free 15/20 minute consultation call with everyone before starting therapy to make sure we are a good fit. Contact me via my website contact form to schedule."

- question: "How long is a typical appointment?"
  answer: |
    The first appointment (Intake) takes 60 minutes. A subsequent regular appointment is 50 minutes. Extended sessions (90 minutes) are available for couples therapy.

    If you feel that a longer session would be helpful for individual work, please don't hesitate to inquire. In some cases — particularly with trauma-focused work — extended sessions may be recommended to allow more time for grounding, deeper processing, and integration. We can discuss whether this might be a good fit based on your needs and therapeutic goals.

- question: "What populations do you serve?"
  answer: "I work with individuals and couples. I primarily work with adults, but in certain circumstances will work with mature adolescents as well. I am inclusive of all gender identities, sexual orientations, cultures, expressions, and ethnicities."

- question: "What do you specialize in?"
  answer: |
    I specialize in trauma, sex, and relationships.
    My clinical foundation is rooted in work with survivors of sexual trauma, and that continues to guide my approach today. I provide trauma-informed therapy for individuals navigating the effects of sexual assault, childhood sexual abuse, incest, sexual repression, or a painful relationship with their body or sexuality. In addition, I offer sex therapy to help clients develop a healthier, more fulfilling relationship with intimacy and desire.

    While many clients initially come to me for support around trauma, sex, or relationships, therapy often evolves beyond those first concerns. As initial goals are met, I continue to work with many clients over the long term — helping them explore broader areas of life, growth, and emotional wellbeing.

    Although I specialize in sex therapy, I am a therapist first. My work is grounded in a relational, whole-person approach, and I talk with clients every day about a wide range of human experiences — including anxiety, depression, family dynamics, work-related stress, identity exploration, and life transitions. Therapy can be a place for healing, but also a space to deepen insight, build resilience, and reconnect with yourself.

- question: "What is sex therapy?"
  answer: |
    Sex therapy is a form of talk therapy that focuses on your relationship with sex, sexuality, and intimacy. It can be done with individuals or couples and provides a safe, nonjudgmental space to explore concerns, questions, or challenges related to your sexual experiences.

    For survivors of sexual trauma, sex therapy can be an empowering part of the healing journey — helping you move beyond trauma, reconnect with your body, and reclaim your sexual self on your own terms.

    While trauma may be a focus for some, I also work with clients around a wide range of sexual concerns, including:

    • Polyamorous and non-monogamous relationships
    • Infidelity and rebuilding trust
    • Erectile dysfunction or performance anxiety
    • Differences in libido or desire
    • Kinks and BDSM
    • Out-of-control or compulsive sexual behavior

    Sex therapy, like all therapy, does not include any kind of nudity or physical touch at any time.

- question: "Do you take insurance?"
  answer: |
    I am an out of network provider. If you're unsure whether your insurance covers out-of-network therapy, it's a good idea to check with them first. While I do not directly bill insurance companies, I am absolutely an insurance friendly practice. Many of my clients use Thrizer for insurance reimbursement.

    https://www.thrizer.com/

    I also accept Victim's Compensation as payment. Please inquire for more information.

- question: "How much does therapy with you cost?"
  answer: |
    Individual Session: (50 min)-$150
    Intake: (60 min)-$175

    Couples:
    Couples Session: (50 minute)-$200
    Intake: (60 min)-$225
    Extended Session: (90 minute)-$275

    I offer a limited number of sliding scale spots for folks in financial need. Please feel free to inquire about availability if cost is a barrier.

    2022 Good Faith Estimate (No Surprises Act):
    You have the right to request a "Good Faith Estimate" of how much your care will cost before your first appointment. If you receive a bill that is at least $400 more than your Good Faith Estimate, you may dispute the bill. For more information about the No Surprise Act, visit www.cms.gov/nosurprises or call 1-877-696-6775.
