- question: "Where are you licensed to work?"
  answer: "I am licensed in Colorado and Washington DC. I offer telehealth appointments."

- question: "Do you offer free consultations to see if we're a good fit?"
  answer: |
    <p>Yes, I offer a free 15/20 minute consultation call with everyone before starting therapy to make sure we are a good fit.</p>

    <p>Contact me via my website <a href="contact" target="_blank" rel="noopener noreferrer">contact form</a> to schedule.</p>

- question: "How long is a typical appointment?"
  answer: |
    <p>The first appointment (Intake) takes 60 minutes. A subsequent regular appointment is 50 minutes. Extended sessions (90 minutes) are available for couples therapy.</p>

    <p>If you feel that a longer session would be helpful for individual work, please don't hesitate to inquire. In some cases — particularly with trauma-focused work — extended sessions may be recommended to allow more time for grounding, deeper processing, and integration. We can discuss whether this might be a good fit based on your needs and therapeutic goals.</p>

- question: "What populations do you serve?"
  answer: "I work with individuals and couples. I primarily work with adults, but in certain circumstances will work with mature adolescents as well. I am inclusive of all gender identities, sexual orientations, cultures, expressions, and ethnicities."

- question: "What do you specialize in?"
  answer: |
    <p>I specialize in trauma, sex, and relationships. My clinical foundation is rooted in work with survivors of sexual trauma, and that continues to guide my approach today. I provide trauma-informed therapy for individuals navigating the effects of sexual assault, childhood sexual abuse, incest, sexual repression, or a painful relationship with their body or sexuality. In addition, I offer sex therapy to help clients develop a healthier, more fulfilling relationship with intimacy and desire.</p>

    <p>While many clients initially come to me for support around trauma, sex, or relationships, therapy often evolves beyond those first concerns. As initial goals are met, I continue to work with many clients over the long term — helping them explore broader areas of life, growth, and emotional wellbeing.</p>

    <p>Although I specialize in sex therapy, I am a therapist first. My work is grounded in a relational, whole-person approach, and I talk with clients every day about a wide range of human experiences — including anxiety, depression, family dynamics, work-related stress, identity exploration, and life transitions. Therapy can be a place for healing, but also a space to deepen insight, build resilience, and reconnect with yourself.</p>

- question: "What is sex therapy?"
  answer: |
    <p>Sex therapy is a form of talk therapy that focuses on your relationship with sex, sexuality, and intimacy. It can be done with individuals or couples and provides a safe, nonjudgmental space to explore concerns, questions, or challenges related to your sexual experiences. For survivors of sexual trauma, sex therapy can be an empowering part of the healing journey — helping you move beyond trauma, reconnect with your body, and reclaim your sexual self on your own terms.</p>

    <p>While trauma may be a focus for some, I also work with clients around a wide range of sexual concerns, including:</p>

    <p>• Polyamorous and non-monogamous relationships<br>
    • Infidelity and rebuilding trust<br>
    • Erectile dysfunction or performance anxiety<br>
    • Differences in libido or desire<br>
    • Kinks and BDSM<br>
    • Out-of-control or compulsive sexual behavior</p>

    <p><strong>Sex therapy, like all therapy, does not include any kind of nudity or physical touch at any time.</strong></p>

- question: "Do you take insurance?"
  answer: |
    <p>I am an out of network provider. If you're unsure whether your insurance covers out-of-network therapy, it's a good idea to check with them first. While I do not directly bill insurance companies, I am absolutely an insurance friendly practice. Many of my clients use <a href="https://www.thrizer.com/" target="_blank" rel="noopener noreferrer">Thrizer</a> for insurance reimbursement.</p>

    <p>I also accept Victim's Compensation as payment. Please inquire for more information.</p>

- question: "How much does therapy with you cost?"
  answer: |
    <p>Please see my <a href="services" target="_blank" rel="noopener noreferrer">Services</a> for exact fees.</p>

    <p>I offer a limited number of sliding scale spots for folks in financial need. Please feel free to inquire about availability if cost is a barrier.</p>

    <p><strong>2022 Good Faith Estimate (No Surprises Act):</strong><br>
    You have the right to request a "Good Faith Estimate" of how much your care will cost before your first appointment. If you receive a bill that is at least $400 more than your Good Faith Estimate, you may dispute the bill. For more information about the No Surprise Act, visit <a href="https://www.cms.gov/nosurprises" target="_blank" rel="noopener noreferrer">www.cms.gov/nosurprises</a> or call 1-877-696-6775.</p>
